### ISSUE TITLE
Roadmap do framework

### ISSUE THREAD

**Issue by Marlysson** [plauzul/phpeasy#1]
Iae man, blz?

Achei a idéia do projeto bem interessante.

Você tem o roadmap de como pretende seguir com o framework? Tipo as funcionalidades.. o que pretende abarcar.. se full ou micro..

**Comment by paulohrdev** [comment]
Opa cara, tipo eu criei esse framework só para uma versão de estudo, eu acho que dependendo da aceitação da comunidade eu poderia tá evoluindo ele. Mas por enquanto penso em terminas uma funcionalidades nele que ainda esta faltando que é o caso da classe Model. Vo criar um .md explicando melhor como ele funciona e como da os primeiros passos, e em como ajudar.
